version: '3.7'

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=examplePassword
      - MYSQL_DATABASE=main
#    volumes:
#      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - db:db
  web:
    build: .
    ports:
      - 5000:5000
    links:
      - db:db
